### ISSUE TITLE
TIARA：Is the retrieved item in Schema Retriever the classes and relations in the entire KG

### ISSUE THREAD

**Issue by LLLLLLoki** [microsoft/KC#20]
This article is very creative and I am very interested.
Is the retrieved item in Schema Retriever the classes and relations in the entire KG？
Are there too many retrieved item candidates?
When will the code for this project be released?

**Comment by HaishuoFang** [comment]
second this

**Comment by ShoRit** [comment]
The code directory for this project has not been updated yet.

**Comment by yhshu** [comment]
> This article is very creative and I am very interested.
> Is the retrieved item in Schema Retriever the classes and relations in the entire KG？
> Are there too many retrieved item candidates?
> When will the code for this project be released?

Thanks for your interest.
We use ~2k classes and ~6k relations for GrailQA setting (ontology is provided by GrailQA), and all the classes and relations for WebQSP.
The efficiency is not a huge concern in our experiments. It takes around 1.4 s per question to inference with an NVIDIA A100 GPU for GrailQA setting.

**Comment by yhshu** [comment]
> second this

Thanks for your interest.
Because of the Microsoft code review process, I have no idea when it would be open source. I believe it will be public soon.

**Comment by tellarin** [comment]
Code has been released. Closing this issue for now. Feel free to open new specific issues with any questions/problems.
