### ISSUE TITLE
[TIARA] Unable to download TIARA_DATA.zip

### ISSUE THREAD

**Issue by jhy12** [microsoft/KC#31]
Hello,

Thank you for sharing your great work!
I've been attempting to follow the instructions in the README.md to run TIARA, but I'm encountering difficulties downloading the TIARA_DATA.zip file.

On Windows, I've tried to download the file by clicking the provided hyperlink multiple times, but without success. Additionally, I attempted to download it on Linux using the following command:
wget https://kcpapers.blob.core.windows.net/tiara-emnlp2022/TIARA_DATA.zip

![image](https://user-images.githubusercontent.com/19502366/234734224-c281bbfa-7268-4622-a39e-70858eb9c6c2.png)

Unfortunately, I continue to face issues. Can you please provide some assistance or guidance on how to resolve this problem? Thank you in advance!

**Comment by yhshu** [comment]
Hi there,
Maybe you need to try another download tool or proxy node.
I am currently able to download fine on macOS Microsoft Edge.

**Comment by jhy12** [comment]
Thank you for the prompt response! Your suggestion helped me understand that the issue stemmed from my network. I successfully downloaded the TIARA_DATA.zip using macOS Microsoft Edge on a different network. I appreciate your assistance!
