### ISSUE TITLE
Link Expired

### ISSUE THREAD

**Issue by Hanzhang-lang** [microsoft/KC#46]
Could the author provide the related weights for rng-kbqa? That link has expired. Thanks very much!

**Comment by Hanzhang-lang** [comment]
Hello, thank you very much for your reply. I now have an additional question. While reproducing your code, I found that the entity linking you provided for the WebQSP dataset differs from the official results from ELQ, i.e., it seems like you're using oracle link results. 
![image](https://github.com/user-attachments/assets/46430ea5-9a51-4e6a-b5e7-62a8a7cf1cdb)
I’d like to wonder if you fine-tuned it again or just upload the wrong file?

**Comment by yhshu** [comment]
Hi, actually you can find released TIARA data in this link: https://drive.google.com/file/d/171vTwW-tO4_5DdEzlYljj2-M3YHvegYF/view
For RnG related data or model, if you don't find them in our link, you may have to contact their authors.

For your second question, they are oracle results, which means they are annotated correct entities for the questions. We convert them into this form for oracle evaluation in our paper.

**Comment by Hanzhang-lang** [comment]
Thanks, so I should go download the non-Oracle version from ELQ's official documents.
