### ISSUE TITLE
Missing information on README file and trained models

### ISSUE THREAD

**Issue by pedroraad** [microsoft/KC#6]
### Missing Information

It seems that in the ReTraCk README, on the "Redis dump files" and "Model checkpoints" sections its missing some informations.
I just want to know if that is a way to disponibilize those parts.

### Trained Models

Complementing that models question, there is a trained model available for public use? If not, how is the correct way to train one?

**Comment by tellarin** [comment]
@pedroraad, thanks for reporting this. Yes, there is a link missing in the README to download all necessary files. Once unzipped locally, the system can be run. Will fix the README shortly. This includes trained models for the two benchmarked datasets.

We'll also soon publish an update documenting how to train new models.

**Comment by pedroraad** [comment]
@tellarin Thank you for the clarification.

Just one more question, with the files already available it's possible to train a new model?

**Comment by tellarin** [comment]
@pedroraad The README has been updated. The repo should contain everything to train a new model.
As mentioned, we'll also publish another update documenting the training process in case there's anything unclear.
