### ISSUE TITLE
ReTraCk resource files

### ISSUE THREAD

**Issue by pedroraad** [microsoft/KC#9]
I'm having problems to download the ReTraCk resource files, it stops every time in 2%,
i already tried to use other computer and other internet provider but is always the same.

It's possible for you to upload those files in other plataform?

**Comment by tellarin** [comment]
Have you tried using curl or wget to resume downloads? I couldn't replicate the problem downloading from multiple locations.

**Comment by pedroraad** [comment]
I managed to download the files but now i'm with another problem.

It seems that the files you provide are still not enough to run the program, i already changed a lot o things to fix the problems i was having but now i can't resolve them.

I would like to know if you can verify if all the code is up to date.

If you want, i can send you an email with somethings that i think its difficult to understand or isn't working.

**Comment by tellarin** [comment]
@pedroraad Thanks for the updare. 

As I menioned, the training code has some issues. But the provided files should be enough to run the demo code (if you set the corresponding environmental variables).

Sorry for the inconvenience. Please reach out by e-mail to me (Börje) and @ArleneYuZhiwei (Zhiwei). You can find our addressed in the commit log.

**Comment by pedroraad** [comment]
Thank's @tellarin again for the clarification.

I sent you a email asking some questions and proposing a meeting just to clear up all the problems i'm having, if it's ok to you.

My email: pedro.raad@ice.ufjf.br
